/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package FineLineGUI;

/**
 * FineLineEventRecord
 * Purpose: stores event data generated by FineLine event extractor tools.
 */
public class FineLineEventRecord 
{
    private String eventID;
    private String eventDescription;
    private String eventType;
    
    public String getEventString(int itemNumber)
    {
        String eventItem = "EMPTY";
        switch(itemNumber)
        {
            
        }
        return eventItem;
    }
    
    public void putEventString(int itemNumber, String itemValue)
    {
        
    }
}
